#!/bin/bash

set -e

rm -rf build dist
python3 up_version.py
python3 -m build
python3 -m twine upload --verbose --repository  pypi dist/*

git add VERSION.txt
git commit -m "version updated";
git push
