# Generated by Django 2.1.7 on 2020-04-22 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ttcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(editable=False, verbose_name='Updated')),
                ('type', models.CharField(max_length=256, verbose_name='Type')),
                ('meta', models.TextField(blank=True, default='')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated'],
                'abstract': False,
            },
        ),
    ]
