# Generated by Django 2.1.7 on 2020-05-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttcore', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='errors',
            field=models.TextField(blank=True, default='', verbose_name='Errors'),
        ),
    ]
